// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer.flex

/*------------  1ra Area: Codigo de Usuario ---------*/
//------> Paquetes,importaciones y declaraciones
package analyst;
import java_cup.runtime.*;
import java.util.LinkedList;

/*------------  2da Area: Opciones y Declaraciones ---------*/

@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  3,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     4,  0,  5,  6,  0,  0,  0,  0,  7,  8,  9, 10,  0, 11, 12, 13, 
    14, 15, 15, 15, 15, 15, 15, 15, 15, 15,  0, 16, 17, 18, 19,  0, 
     0, 20, 21, 22, 23, 24, 25, 26, 27, 28, 26, 26, 29, 30, 31, 32, 
    33, 26, 34, 35, 36, 26, 26, 26, 26, 26, 26,  0,  0,  0,  0, 37, 
     0, 20, 21, 22, 23, 24, 25, 26, 27, 28, 26, 26, 29, 30, 31, 32, 
    33, 26, 34, 35, 36, 26, 26, 26, 26, 26, 26,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0, 38,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\14\1\15\1\16"+
    "\1\17\11\20\2\0\12\20\1\21\1\22\1\23\15\20"+
    "\1\0\10\20\1\24\1\20\1\25\1\26\1\20\1\0"+
    "\4\20\1\27\1\20\1\30\1\31\1\20\1\32\1\0"+
    "\1\33\5\20\1\0\2\20\1\34\2\20\1\35\1\36"+
    "\1\20\1\37\1\40\2\20\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\50\0\50\0\120\0\170\0\50\0\50"+
    "\0\50\0\50\0\50\0\50\0\240\0\310\0\50\0\50"+
    "\0\50\0\50\0\360\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8"+
    "\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8"+
    "\0\u0320\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438"+
    "\0\50\0\u0280\0\u0460\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528"+
    "\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668"+
    "\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0780\0\u07a8"+
    "\0\360\0\u07d0\0\360\0\360\0\u07f8\0\u0820\0\u0848\0\u0870"+
    "\0\u0898\0\u08c0\0\360\0\u08e8\0\360\0\360\0\u0910\0\360"+
    "\0\u0938\0\360\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28"+
    "\0\u0a50\0\u0a78\0\360\0\u0aa0\0\u0ac8\0\50\0\360\0\u0af0"+
    "\0\360\0\360\0\u0b18\0\u0b40\0\360";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\2\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\23\1\24\1\23\1\25\1\26"+
    "\1\23\1\27\1\23\1\30\1\31\2\23\1\32\1\23"+
    "\1\33\2\23\1\0\1\2\51\0\4\34\11\0\2\34"+
    "\4\0\21\34\1\0\2\34\2\6\2\0\42\6\1\0"+
    "\1\6\14\0\1\35\47\0\1\35\1\0\2\16\46\0"+
    "\2\23\4\0\21\23\21\0\2\23\4\0\1\36\13\23"+
    "\1\37\4\23\21\0\2\23\4\0\13\23\1\40\3\23"+
    "\1\41\1\23\21\0\2\23\4\0\10\23\1\42\1\43"+
    "\7\23\21\0\2\23\4\0\1\44\20\23\21\0\2\23"+
    "\4\0\4\23\1\45\14\23\21\0\2\23\4\0\10\23"+
    "\1\46\10\23\21\0\2\23\4\0\1\47\20\23\21\0"+
    "\2\23\4\0\10\23\1\50\10\23\4\0\4\34\1\51"+
    "\10\0\2\34\4\0\21\34\1\0\2\34\16\0\2\52"+
    "\46\0\2\23\4\0\3\23\1\53\15\23\21\0\2\23"+
    "\4\0\13\23\1\54\5\23\21\0\2\23\4\0\20\23"+
    "\1\55\21\0\2\23\4\0\2\23\1\56\16\23\21\0"+
    "\2\23\4\0\13\23\1\57\5\23\21\0\2\23\4\0"+
    "\14\23\1\60\4\23\21\0\2\23\4\0\2\23\1\61"+
    "\14\23\1\62\1\23\21\0\2\23\4\0\4\23\1\63"+
    "\14\23\21\0\2\23\4\0\4\23\1\64\14\23\21\0"+
    "\2\23\4\0\16\23\1\65\2\23\21\0\2\23\4\0"+
    "\13\23\1\66\5\23\21\0\2\23\4\0\4\23\1\67"+
    "\14\23\7\0\1\70\11\0\2\23\4\0\21\23\21\0"+
    "\2\23\4\0\4\23\1\71\14\23\21\0\2\23\4\0"+
    "\16\23\1\72\2\23\21\0\2\23\4\0\12\23\1\73"+
    "\2\23\1\74\1\23\1\75\1\23\21\0\2\23\4\0"+
    "\20\23\1\76\21\0\2\23\4\0\4\23\1\77\14\23"+
    "\21\0\2\23\4\0\20\23\1\100\21\0\2\23\4\0"+
    "\16\23\1\101\2\23\21\0\2\23\4\0\13\23\1\102"+
    "\5\23\21\0\2\23\4\0\1\103\20\23\21\0\2\23"+
    "\4\0\14\23\1\104\4\23\21\0\2\23\4\0\13\23"+
    "\1\105\5\23\44\0\1\106\24\0\2\23\4\0\16\23"+
    "\1\107\2\23\21\0\2\23\4\0\10\23\1\110\10\23"+
    "\21\0\2\23\4\0\10\23\1\111\10\23\21\0\2\23"+
    "\4\0\1\112\20\23\21\0\2\23\4\0\10\23\1\113"+
    "\10\23\21\0\2\23\4\0\1\114\20\23\21\0\2\23"+
    "\4\0\16\23\1\115\2\23\21\0\2\23\4\0\1\116"+
    "\20\23\21\0\2\23\4\0\20\23\1\117\21\0\2\23"+
    "\4\0\1\120\20\23\27\0\1\121\41\0\2\23\4\0"+
    "\14\23\1\122\4\23\21\0\2\23\4\0\1\23\1\123"+
    "\17\23\21\0\2\23\4\0\4\23\1\124\14\23\21\0"+
    "\2\23\4\0\16\23\1\125\2\23\21\0\2\23\4\0"+
    "\13\23\1\126\5\23\21\0\2\23\4\0\16\23\1\127"+
    "\2\23\46\0\1\130\22\0\2\23\4\0\10\23\1\131"+
    "\10\23\21\0\2\23\4\0\13\23\1\132\5\23\21\0"+
    "\2\23\4\0\1\133\20\23\21\0\2\23\4\0\20\23"+
    "\1\134\21\0\2\23\4\0\1\135\20\23\43\0\1\136"+
    "\25\0\2\23\4\0\16\23\1\137\2\23\21\0\2\23"+
    "\4\0\20\23\1\140\21\0\2\23\4\0\4\23\1\141"+
    "\14\23\21\0\2\23\4\0\17\23\1\142\1\23\21\0"+
    "\2\23\4\0\16\23\1\143\2\23\21\0\2\23\4\0"+
    "\1\144\20\23\21\0\2\23\4\0\17\23\1\145\1\23"+
    "\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2920];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\2\1\6\11\2\1\4\11\11\1\2\0"+
    "\13\1\1\11\16\1\1\0\15\1\1\0\12\1\1\0"+
    "\6\1\1\0\5\1\1\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[101];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    //----> Codigo de usuario en sintaxis java
    public static LinkedList<TError> TablaEL = new LinkedList<TError>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error Lexico"+yytext()+" Linea "+yyline+" Columna "+yycolumn);
                          TError datos = new TError(yytext(),yyline,yycolumn,"Error Lexico","Simbolo no existe en el lenguaje");
                          TablaEL.add(datos);
            }
          // fall through
          case 34: break;
          case 2:
            { 
            }
          // fall through
          case 35: break;
          case 3:
            { /* Espacios en blanco, se ignoran */
            }
          // fall through
          case 36: break;
          case 4:
            { /*Ignore*/
            }
          // fall through
          case 37: break;
          case 5:
            { System.out.println("Encontro "+yytext()+"parenta" ); return new Symbol(sym.parenta, yycolumn, yyline, yytext());
            }
          // fall through
          case 38: break;
          case 6:
            { System.out.println("Encontro "+yytext()+"parentc" ); return new Symbol(sym.parentc, yycolumn, yyline, yytext());
            }
          // fall through
          case 39: break;
          case 7:
            { System.out.println("Encontro "+yytext()+"mult" ); return new Symbol(sym.mult, yycolumn, yyline, yytext());
            }
          // fall through
          case 40: break;
          case 8:
            { System.out.println("Encontro "+yytext()+"mas" ); return new Symbol(sym.mas, yycolumn, yyline, yytext());
            }
          // fall through
          case 41: break;
          case 9:
            { System.out.println("Encontro "+yytext()+"menos" ); return new Symbol(sym.menos, yycolumn, yyline, yytext());
            }
          // fall through
          case 42: break;
          case 10:
            { System.out.println("Encontro "+yytext()+"div" ); return new Symbol(sym.div, yycolumn, yyline, yytext());
            }
          // fall through
          case 43: break;
          case 11:
            { System.out.println("Reconocio "+yytext()+" numero"); return new Symbol(sym.numero, Integer.valueOf(yytext()));
            }
          // fall through
          case 44: break;
          case 12:
            { System.out.println("Encontro "+yytext()+"puntocoma" ); return new Symbol(sym.puntocoma, yycolumn, yyline, yytext());
            }
          // fall through
          case 45: break;
          case 13:
            { System.out.println("Encontro "+yytext()+"menor" ); return new Symbol(sym.menor, yycolumn, yyline, yytext());
            }
          // fall through
          case 46: break;
          case 14:
            { System.out.println("Encontro "+yytext()+"igual" ); return new Symbol(sym.igual, yycolumn, yyline, yytext());
            }
          // fall through
          case 47: break;
          case 15:
            { System.out.println("Encontro "+yytext()+"mayor" ); return new Symbol(sym.mayor, yycolumn, yyline, yytext());
            }
          // fall through
          case 48: break;
          case 16:
            { System.out.println("Reconocio "+yytext()+" id"); return new Symbol(sym.id, yycolumn, yyline, yytext());
            }
          // fall through
          case 49: break;
          case 17:
            { System.out.println("Reconocio "+yytext()+" si"); return new Symbol(sym.SI, yycolumn, yyline, yytext());
            }
          // fall through
          case 50: break;
          case 18:
            { System.out.println("Reconocio "+yytext()+" comilla"); return new Symbol(sym.comilla, yycolumn, yyline, yytext());
            }
          // fall through
          case 51: break;
          case 19:
            { System.out.println("Reconocio "+yytext()+" decimal"); return new Symbol(sym.decimal, Double.valueOf(yytext()));
            }
          // fall through
          case 52: break;
          case 20:
            { System.out.println("Reconocio "+yytext()+" leer"); return new Symbol(sym.LEER, yycolumn, yyline, yytext());
            }
          // fall through
          case 53: break;
          case 21:
            { System.out.println("Reconocio "+yytext()+" para"); return new Symbol(sym.PARA, yycolumn, yyline, yytext());
            }
          // fall through
          case 54: break;
          case 22:
            { System.out.println("Reconocio "+yytext()+" sino"); return new Symbol(sym.SINO, yycolumn, yyline, yytext());
            }
          // fall through
          case 55: break;
          case 23:
            { System.out.println("Reconocio "+yytext()+" finsi"); return new Symbol(sym.FINSI, yycolumn, yyline, yytext());
            }
          // fall through
          case 56: break;
          case 24:
            { System.out.println("Reconocio "+yytext()+" hacer"); return new Symbol(sym.HACER, yycolumn, yyline, yytext());
            }
          // fall through
          case 57: break;
          case 25:
            { System.out.println("Reconocio "+yytext()+" hasta"); return new Symbol(sym.HASTA, yycolumn, yyline, yytext());
            }
          // fall through
          case 58: break;
          case 26:
            { System.out.println("Reconocio "+yytext()+" cadena"); return new Symbol(sym.CADENA, yycolumn, yyline, yytext());
            }
          // fall through
          case 59: break;
          case 27:
            { System.out.println("Reconocio "+yytext()+" entero"); return new Symbol(sym.ENTERO, yycolumn, yyline, yytext());
            }
          // fall through
          case 60: break;
          case 28:
            { System.out.println("Reconocio "+yytext()+" finpara"); return new Symbol(sym.FINPARA, yycolumn, yyline, yytext());
            }
          // fall through
          case 61: break;
          case 29:
            { System.out.println("Reconocio "+yytext()+" con paso"); return new Symbol(sym.CON_PASO, yycolumn, yyline, yytext());
            }
          // fall through
          case 62: break;
          case 30:
            { System.out.println("Reconocio "+yytext()+" escribir"); return new Symbol(sym.ESCRIBIR, yycolumn, yyline, yytext());
            }
          // fall through
          case 63: break;
          case 31:
            { System.out.println("Reconocio "+yytext()+" flotante"); return new Symbol(sym.FLOTANTE, yycolumn, yyline, yytext());
            }
          // fall through
          case 64: break;
          case 32:
            { System.out.println("Reconocio "+yytext()+" mientras"); return new Symbol(sym.MIENTRAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 65: break;
          case 33:
            { System.out.println("Reconocio "+yytext()+" finmientras"); return new Symbol(sym.FINMIENTRAS, yycolumn, yyline, yytext());
            }
          // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
