
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyst;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int comilla = 2;
  public static final int CADENA = 17;
  public static final int decimal = 29;
  public static final int numero = 28;
  public static final int parentc = 23;
  public static final int HASTA = 10;
  public static final int LEER = 4;
  public static final int mult = 20;
  public static final int parenta = 22;
  public static final int FLOTANTE = 16;
  public static final int PARA = 8;
  public static final int menos = 19;
  public static final int menor = 26;
  public static final int div = 21;
  public static final int igual = 25;
  public static final int EOF = 0;
  public static final int FINMIENTRAS = 14;
  public static final int id = 30;
  public static final int SINO = 6;
  public static final int puntocoma = 24;
  public static final int SI = 5;
  public static final int ESCRIBIR = 3;
  public static final int error = 1;
  public static final int CON_PASO = 12;
  public static final int FINPARA = 9;
  public static final int ENTERO = 15;
  public static final int mas = 18;
  public static final int MIENTRAS = 13;
  public static final int FINSI = 7;
  public static final int HACER = 11;
  public static final int mayor = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "comilla",
  "ESCRIBIR",
  "LEER",
  "SI",
  "SINO",
  "FINSI",
  "PARA",
  "FINPARA",
  "HASTA",
  "HACER",
  "CON_PASO",
  "MIENTRAS",
  "FINMIENTRAS",
  "ENTERO",
  "FLOTANTE",
  "CADENA",
  "mas",
  "menos",
  "mult",
  "div",
  "parenta",
  "parentc",
  "puntocoma",
  "igual",
  "menor",
  "mayor",
  "numero",
  "decimal",
  "id"
  };
}

