
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyst;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 3;
  public static final int POR = 8;
  public static final int CONCAT = 10;
  public static final int ENTERO = 18;
  public static final int RSEGUN = 36;
  public static final int PUNTOCOMA = 2;
  public static final int IDENTIFICADOR = 41;
  public static final int RMIENTRAS = 28;
  public static final int IGUAL = 40;
  public static final int RESCRIBIR = 27;
  public static final int FUN = 24;
  public static final int CARACTER = 20;
  public static final int RDEFECTO = 39;
  public static final int RENTERO = 29;
  public static final int RLEER = 26;
  public static final int DIV = 9;
  public static final int RCONPASO = 35;
  public static final int INCREMENTO = 12;
  public static final int RPARA = 34;
  public static final int MAIN = 25;
  public static final int UMENOS = 23;
  public static final int PARENTC = 5;
  public static final int PARENTA = 4;
  public static final int EOF = 0;
  public static final int DECIMAL = 19;
  public static final int DECREMENTO = 13;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 22;
  public static final int MENOS = 7;
  public static final int MENOR = 14;
  public static final int RHASTA = 33;
  public static final int RSI = 30;
  public static final int MAYOR = 15;
  public static final int RCASE = 37;
  public static final int RCADENA = 32;
  public static final int RSINO = 31;
  public static final int RFLOTANTE = 21;
  public static final int RBREAK = 38;
  public static final int LLAVEB = 17;
  public static final int LLAVEA = 16;
  public static final int MAS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "PARENTA",
  "PARENTC",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "CONCAT",
  "COMA",
  "INCREMENTO",
  "DECREMENTO",
  "MENOR",
  "MAYOR",
  "LLAVEA",
  "LLAVEB",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "RFLOTANTE",
  "CADENA",
  "UMENOS",
  "FUN",
  "MAIN",
  "RLEER",
  "RESCRIBIR",
  "RMIENTRAS",
  "RENTERO",
  "RSI",
  "RSINO",
  "RCADENA",
  "RHASTA",
  "RPARA",
  "RCONPASO",
  "RSEGUN",
  "RCASE",
  "RBREAK",
  "RDEFECTO",
  "IGUAL",
  "IDENTIFICADOR"
  };
}

